# Shell variables
# Generated by 'wal'
wallpaper='/home/sinh/Pictures/Wallpapers/wallhaven-k7jgp7-3782x2521.jpeg'

# Special
background='#391b0b'
foreground='#f3ecdf'
cursor='#f3ecdf'

# Colors
color0='#391b0b'
color1='#E4A85F'
color2='#F3AF71'
color3='#BDA089'
color4='#EEB48A'
color5='#F7CC92'
color6='#F7D9AD'
color7='#f3ecdf'
color8='#aaa59c'
color9='#E4A85F'
color10='#F3AF71'
color11='#BDA089'
color12='#EEB48A'
color13='#F7CC92'
color14='#F7D9AD'
color15='#f3ecdf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
