#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/niri"
RASI="$DIR/rofi/powermenu.rasi"
CNFR="$DIR/rofi/confirm.rasi"

# Theme Elements
prompt="`hostname` (`echo $DESKTOP_SESSION`)"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options (Order: Lock, Sleep, Logout, Reboot, Shutdown)
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1="󰌾 Lock"
	option_2="󰒲 Sleep"
	option_3="󰗽 Logout"
	option_4="󰜉 Reboot"
	option_5="󰐥 Shutdown"
else
	option_1="󰌾"
	option_2="󰒲"
	option_3="󰗽"
	option_4="󰜉"
	option_5="󰐥"
fi
cnflayout=`cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$cnflayout" == 'NO' ]]; then
	yes='󰄬 Yes'
	no='󰜺 No'
else
	yes='󰄬'
	no='󰜺'
fi

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Confirmation CMD
confirm_cmd() {
	rofi -dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-selected-row 1 \
		-no-click-to-exit \
		-theme ${CNFR}
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Confirm and execute
confirm_run () {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
        ${1} && ${2} && ${3} && ${4}
    else
        exit
    fi
}

no_confirm_run () {
  ${1} && ${2} && ${3} && ${4}
}

# Execute Command
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		# Lock screen using swaylock
		swaylock
	elif [[ "$1" == '--opt2' ]]; then
		# Sleep/Suspend
		no_confirm_run 'mpc -q pause' 'pulsemixer --mute' 'systemctl suspend'
	elif [[ "$1" == '--opt3' ]]; then
		# Logout from Niri
		niri msg action quit
	elif [[ "$1" == '--opt4' ]]; then
		no_confirm_run 'systemctl reboot'
	elif [[ "$1" == '--opt5' ]]; then
		no_confirm_run 'systemctl poweroff'
	fi
}

# Actions
chosen="$(run_rofi)"

# Exit if no selection (ESC pressed)
[[ -z "$chosen" ]] && exit 0

case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
esac
